apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "eric-oss.name" . }}-gas-patcher-hook
  labels:
    {{- include "eric-oss.kubernetes-io-info" .| nindent 4 }}
  annotations:
    {{- include "eric-oss.helm-annotations" .| nindent 4 }}
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ template "eric-oss.name" . }}-gas-patcher-new-sa
      {{- if include "eric-oss.gas-patcher.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ template "eric-oss.gas-patcher.pullSecrets" . }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: gas-patcher-hook
        image: {{ template "eric-oss.gas-patcher-path" . }}
        imagePullPolicy: {{ index .Values "imageCredentials" "gas-patcher" "registry" "imagePullPolicy" }}
        volumeMounts:
        - name: patching-configuration-volume
          mountPath: /tmp
        env:
        - name: GAS_CONFIGMAP
          value: "eric-adp-gui-aggregator-service-configmap"
        - name: THIS_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: GAS_CONFIG_FILENAME
          value: "manualconfig.json"
        securityContext:
          allowPrivilegeEscalation: true
          runAsNonRoot: false
          runAsUser: 0
        resources:
          limits:
            cpu: 0.2
            memory: 100Mi
          requests:
            cpu: 0.02
            memory: 80Mi
      {{- include "eric-oss.nodeSelector" .| indent 6 }}
      volumes:
      - name: patching-configuration-volume
        configMap:
          name: {{ template "eric-oss.name" . }}-gas-patcher-configmap
          defaultMode: 0777
      restartPolicy: Never
  backoffLimit: 3
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "eric-oss.name" . }}-gas-backup-hook
  labels:
    {{- include "eric-oss.kubernetes-io-info" .| nindent 4 }}
  annotations:
    {{- include "eric-oss.helm-annotations" .| nindent 4 }}
    "helm.sh/hook": pre-upgrade, pre-rollback
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ template "eric-oss.name" . }}-gas-patcher-new-sa
      {{- if include "eric-oss.gas-patcher.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ template "eric-oss.gas-patcher.pullSecrets" . }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: gas-patcher-hook
        image: {{ template "eric-oss.gas-patcher-path" . }}
        args:
        - "--backup"
        imagePullPolicy: {{ index .Values "imageCredentials" "gas-patcher" "registry" "imagePullPolicy" }}
        env:
        - name: GAS_CONFIGMAP
          value: "eric-adp-gui-aggregator-service-configmap"
        - name: THIS_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: GAS_CONFIG_FILENAME
          value: "manualconfig.json"
        securityContext:
          allowPrivilegeEscalation: true
          runAsNonRoot: false
          runAsUser: 0
        resources:
          limits:
            cpu: 0.2
            memory: 100Mi
          requests:
            cpu: 0.02
            memory: 80Mi
      {{- include "eric-oss.nodeSelector" .| indent 6 }}
      restartPolicy: Never
  backoffLimit: 3
