dependencies:
- name: eric-eo-so
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm/
  tags:
  - so
  version: 2.11.0-293
- name: eric-oss-pf
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm
  tags:
  - pf
  version: 1.14.0-11
- name: eric-oss-uds
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm
  tags:
  - uds
  version: 3.4.0-15
- name: eric-eo-api-gateway
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm/
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 3.0.0-3
- condition: keycloak.enabled
  name: eric-sec-access-mgmt
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 8.1.0+21
- alias: idam-database-pg
  condition: keycloak.enabled
  name: eric-data-document-database-pg
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 6.0.0+65
- condition: logging.enabled
  name: eric-data-search-engine
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 7.1.0+11
- condition: logging.enabled
  name: eric-data-search-engine-curator
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 2.5.0+23
- condition: logging.enabled
  name: eric-log-shipper
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 6.1.0+13
- condition: logging.enabled
  name: eric-log-transformer
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 6.0.0+30
- condition: logging.enabled
  name: eric-data-visualizer-kb
  repository: https://arm.epk.ericsson.se/artifactory/proj-eo-released-helm/
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 22.6.0+1
- condition: eric-pm-server.enabled
  name: eric-pm-server
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 6.2.0+28
- name: eric-eo-usermgmt
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm/
  tags:
  - so
  - pf
  - platform
  - adc
  - dmm
  - th
  - uds
  - eas
  version: 1.0.1-38
- name: eric-eo-usermgmt-ui
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm
  tags:
  - so
  - pf
  - platform
  - adc
  - dmm
  - th
  - uds
  - eas
  version: 1.0.0-94
- condition: eai.enabled
  name: eric-eo-eai
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm
  tags:
  - so
  version: 1.0.2-147
- alias: eric-eo-eai-database-pg
  name: eric-data-document-database-pg
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - so
  version: 6.0.0+65
- condition: backup-controller.enabled
  name: eric-ctrl-bro
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - so
  - platform
  - uds
  - adc
  - dmm
  - th
  - eas
  version: 4.6.0+38
- name: eric-oss-dmaap
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm
  tags:
  - pf
  - uds
  - so
  - eas
  version: 1.0.0-56
- name: eric-data-message-bus-kf
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - pf
  - uds
  - so
  - adc
  - dmm
  - th
  - eas
  version: 1.16.0+27
- name: eric-data-coordinator-zk
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - pf
  - uds
  - so
  - adc
  - dmm
  - th
  - eas
  version: 1.18.0+19
- condition: backup-controller.enabled
  name: eric-eo-common-br-agent
  repository: https://arm.epk.ericsson.se/artifactory/proj-eo-drop-helm/
  tags:
  - so
  - platform
  version: 1.0.0-112
- alias: eric-oss-common-postgres
  name: eric-data-document-database-pg
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 6.0.0+65
- name: eric-adp-gui-aggregator-service
  repository: https://arm.epk.ericsson.se/artifactory/proj-eea-released-helm
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 0.6.0+40
- alias: eric-oss-notification-service-database-pg
  condition: notification-service.enabled
  name: eric-data-document-database-pg
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - so
  - eas
  version: 6.0.0+65
- condition: notification-service.enabled
  name: eric-oss-notification-service
  repository: https://arm.seli.gic.ericsson.se/artifactory/proj-eo-drop-helm/
  tags:
  - so
  - eas
  version: 1.0.0-180
- name: eric-eo-ecmsol005-adapter
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm
  tags:
  - so
  - uds
  version: 1.4.0-7
- condition: stubs.enabled
  name: eric-eo-ecmsol005-stub
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm
  tags:
  - so
  - uds
  version: 1.0.0-65
- condition: eric-tm-ingress-controller-cr.enabled
  name: eric-tm-ingress-controller-cr
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - so
  - pf
  - uds
  - platform
  - adc
  - dmm
  - th
  - eas
  version: 5.6.0+26
- name: eric-eo-subsystem-management
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm/
  tags:
  - so
  - uds
  - platform
  - eas
  version: 2.4.1-22
- alias: eric-eo-subsystem-management-database-pg
  name: eric-data-document-database-pg
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  tags:
  - so
  - uds
  - platform
  - eas
  version: 6.0.0+65
- name: eric-eo-subsystemsmgmt-ui
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm
  tags:
  - so
  - uds
  version: 1.4.0-9
- name: eric-eo-credential-manager
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm
  tags:
  - so
  - uds
  version: 1.4.1-3
- name: eric-eo-onboarding
  repository: https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-so-gs-all-helm
  tags:
  - so
  - uds
  version: 1.4.1-15
- name: eric-oss-adc
  repository: https://arm.seli.gic.ericsson.se/artifactory/proj-eric-oss-drop-helm-local
  tags:
  - adc
  version: 0.0.2-2
- name: eric-oss-dmm
  repository: https://arm.seli.gic.ericsson.se/artifactory/proj-eric-oss-drop-helm
  tags:
  - dmm
  - adc
  version: 0.0.0-17
- name: eric-topology-handling
  repository: https://arm.seli.gic.ericsson.se/artifactory/proj-eric-oss-drop-helm
  tags:
  - th
  version: 0.0.2-3
- name: eric-oss-ericsson-adaptation
  repository: https://arm.seli.gic.ericsson.se/artifactory/proj-eric-oss-drop-helm
  tags:
  - eas
  version: 0.1.0-12
