#
# COPYRIGHT Ericsson 2019
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
{{ $backup := include "eric-oss.backup-controller.enabled" . }}
{{ if eq $backup "true" -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "eric-oss.name" . }}-ctrl-bro-rbac-configmap
  labels:
  {{- include "eric-oss.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss.helm-annotations" .| nindent 4 }}
data:
  eric-ctrl-bro-rbac-configuration.json: |
    {
      "roles": [
          {
            "name": "EO Admin",
            "attributes": {},
            "composites": {
              "realm": [],
              "client": {}
            }
          }
        ],
      "authorization":
      {
        "resources": [
          {
            "name": "Backup and Restore",
            "type": "urn:eo:resources:bur",
            "ownerManagedAccess": false,
            "displayName": "Backup and Restore",
            "attributes": {},
            "uris": [
               {{ template "eric-oss.bur.rbac-resources" .}}
            ],
            "scopes": [{
                    "name": "PATCH"
                }, {
                    "name": "DELETE"
                }, {
                    "name": "GET"
                }, {
                    "name": "POST"
                }, {
                    "name": "PUT"
                }
            ]
          }
        ],
        "policies": [
          {
            "name": "Is EO Admin Policy",
            "description": "Policy for EO Admin that is based on role",
            "type": "role",
            "logic": "POSITIVE",
            "decisionStrategy": "UNANIMOUS",
            "config": {
              "roles": "[{\"id\":\"EO Admin\",\"required\":false}]"
            }
          },
          {
            "name": "EO Admin Permission",
            "description": "Permission to EO Admin",
            "type": "scope",
            "logic": "POSITIVE",
            "decisionStrategy": "UNANIMOUS",
            "config": {
              "resources": "[\"Backup and Restore\"]",
              "scopes": "[\"GET\",\"PUT\",\"POST\",\"DELETE\",\"PATCH\"]",
              "applyPolicies": "[\"Is EO Admin Policy\"]"
            }
          }
        ],
        "scopes": [{
                "name": "GET"
            }, {
                "name": "POST"
            }, {
                "name": "DELETE"
            }, {
                "name": "PUT"
            }, {
                "name": "PATCH"
            }
        ]
      }
    }
{{- end -}}