{{- if .Values.global.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-oss.name" . }}-subsystem-management-database-pg-limit-internal-traffic
  labels:
    chart: {{ template "eric-oss.chart" . }}
  {{- include "eric-oss.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss.helm-annotations" .| nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: eric-eo-subsystem-management-database-pg
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: eric-eo-subsystem-management
    - podSelector:
        matchLabels:
          app: eric-eo-subsystem-management-database-pg
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: eric-ctrl-bro
    - podSelector:
        matchLabels:
          app: eric-eo-subsystem-management-database-pg-bragent
    - podSelector:
        matchLabels:
          app: eric-pm-server
{{- end }}
