{{- if .Values.global.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-oss.name" . }}-subsystem-management-limit-internal-traffic
  labels:
    {{- include "eric-oss.kubernetes-io-info" .| nindent 4 }}
  annotations:
    {{- include "eric-oss.helm-annotations" .| nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: eric-eo-subsystem-management
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: eric-eo-api-gateway
    - podSelector:
        matchLabels:
          app: eric-eo-engine
    - podSelector:
        matchLabels:
          app: eric-eo-workflow
    - podSelector:
        matchLabels:
          app: eric-eo-so-l3nm-netfusion-adapter
    - podSelector:
        matchLabels:
          app: eric-eo-ecm-adapter
    - podSelector:
        matchLabels:
          app: eric-eo-ecmsol005-adapter
    - podSelector:
        matchLabels:
          app: eric-eo-sol005-adapter
    - podSelector:
        matchLabels:
          app: eric-eo-onboarding
    - podSelector:
        matchLabels:
          app: eric-eo-enm-adapter
    - podSelector:
        matchLabels:
          job-name: eric-eo-subsystem-migration
    - podSelector:
        matchLabels:
          app: eric-pm-server
    - podSelector:
        matchLabels:
           app: eric-eo-playbook-service
    - podSelector:
        matchLabels:
           app: eric-eo-ipaddress-manager
    - podSelector:
        matchLabels:
          app: eric-eo-eai-adapter
    - podSelector:
        matchLabels:
          app: eric-oss-adc-ems-notification-collector
  {{- if .Values.global.developmentEnabled }}
  - ports:
    - port: 8080
  {{- end }}
{{- end }}
