{{ if .Values.global.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-oss.name" . }}-eric-tm-ingress-controller-cr-contour-limit-internal-traffic
  labels:
  {{- include "eric-oss.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss.helm-annotations" .| nindent 4 }}
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      app: eric-tm-ingress-controller-cr-contour
  policyTypes:
  - Ingress
{{- end }}
