#
# COPYRIGHT Ericsson 2019
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if .Values.global.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-oss.name" . }}-eric-eo-api-gateway-allow-external-traffic
  labels:
  {{- include "eric-oss.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss.helm-annotations" .| nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: eric-eo-api-gateway
  ingress:
  # ALLOW traffic from external clients
  - from: []
    ports:
      # Workaround required for Topology-handling app (and its eai component).
      # Race condition and conflict between Hazelcast versions occurs if leave port 5701 open.
    - protocol: TCP
      port: 8080
{{- end }}
