{{- if .Values.global.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-oss.name" . }}-common-br-agent-limit-internal-traffic
  labels:
  {{- include "eric-oss.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss.helm-annotations" .| nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: eric-eo-common-br-agent
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: eric-eo-common-br-agent
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: eric-ctrl-bro
{{- end }}
