kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "eric-oss.release.name" . }}-gas-patcher-new-policy
  labels:
  {{- include "eric-oss.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss.helm-annotations" .| nindent 4 }}
    "helm.sh/hook": pre-install, pre-upgrade, pre-rollback, post-install, post-upgrade, post-rollback
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
# Rule to allow GAS hook to patch its ext app configmap
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - configmaps
    verbs:
      - get
      - list
      - patch
      - create
      - delete
